### PR TITLE
new

### PR DESCRIPTION
**Pull request by philipto1**

### CODE REVIEW

**Comment by philipto1** [comment]
test

**Comment by philipto** [comment]
email.txt     : this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
I am sorry, the domain vccs.edu is blacklisted because the school allows to register an email address there even if you are not a student  of the school. If you are the student of this school, please apply with official document.

**Comment by philipto** [comment]
I am sorry, the domain vccs.edu is blacklisted because the school allows to register an email address there even if you are not a student  of the school. If you are the student of this school, please apply with official document.

**Comment by philipto** [comment]
I am sorry, the domain vccs.edu is blacklisted because the school allows to register an email address there even if you are not a student of the school. If you are the student of this school, please apply with official document (OFFICIAL DOCUMENT tab at https://www.jetbrains.com/shop/eform/students).

**Comment by philipto** [comment]
I am sorry, the domain sharif.edu is blacklisted because the school allows to register an email address there even if you are not a student of the school. If you are the student of this school, please apply with official document (OFFICIAL DOCUMENT tab at https://www.jetbrains.com/shop/eform/students).

**Comment by philipto** [comment]
I am sorry, the domain sharif.edu is blacklisted because the school allows to register an email address there even if you are not a student of the school. If you are the student of this school, please apply with official document (OFFICIAL DOCUMENT tab at https://www.jetbrains.com/shop/eform/students).

**Comment by philipto** [comment]
I am sorry, the domain sharif.edu is blacklisted because the school allows to register an email address there even if you are not a student of the school. If you are the student of this school, please apply with official document (OFFICIAL DOCUMENT tab at https://www.jetbrains.com/shop/eform/students).

**Comment by philipto** [comment]
I am sorry, the domain sharif.edu is blacklisted because the school allows to register an email address there even if you are not a student of the school. If you are the student of this school, please apply with official document (OFFICIAL DOCUMENT tab at https://www.jetbrains.com/shop/eform/students).

**Comment by philipto** [comment]
I am sorry, the domain sharif.edu is blacklisted because the school allows to register an email address there even if you are not a student of the school. If you are the student of this school, please apply with official document (OFFICIAL DOCUMENT tab at https://www.jetbrains.com/shop/eform/students).

**Comment by philipto** [comment]
I am sorry, the domain vccs.edu is blacklisted because the school allows to register an email address there even if you are not a student of the school. If you are the student of this school, please apply with official document (OFFICIAL DOCUMENT tab at https://www.jetbrains.com/shop/eform/students).

**Pull request closed without merging**
