### PR TITLE
Create supdepub.txt

### PR DESCRIPTION
**Pull request by philipto2**
Supdepub please

### CODE REVIEW

**Comment by philipto2** [comment]
Aluno

**Comment by philipto2** [comment]
Aluno

**Comment by philipto** [comment]
$TXT_PATH_INCORRECT

**Comment by philipto** [comment]
$TXT_PATH_INCORRECT

**Comment by philipto** [comment]
$TXT_PATH_INCORRECT

**Comment by philipto** [comment]
$TXT_PATH_INCORRECT

**Comment by philipto** [comment]
$TXT_PATH_INCORRECT

**Comment by philipto** [comment]
$TXT_PATH_INCORRECT

**Comment by philipto** [comment]
$TXT_PATH_INCORRECT

**Comment by philipto** [comment]
text

**Comment by philipto** [comment]
TXT_NONEXISTENT_HOST

**Comment by philipto** [comment]
The domain does not exist: Host supdepub.fr not found: 2(SERVFAIL)

**Comment by philipto** [comment]
The domain does not exist: Host supdepub.fr not found: 2(SERVFAIL)

**Comment by philipto** [comment]
The domain does not exist: Host supdepub.fr not found: 2(SERVFAIL)

**Comment by philipto** [comment]
The domain does not exist: Host supdepub.fr not found: 2(SERVFAIL)

**Comment by philipto** [comment]
The domain does not exist: Host supdepub.fr not found: 2(SERVFAIL)

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: Host supdepub.fr not found: 2(SERVFAIL) Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
lib/domains/br/com/alunofpb.txt path is incorrect

**Comment by philipto** [comment]
lib/domains/fr/supdepub.txt path is incorrect

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: Host supdepub.fr not found: 2(SERVFAIL) Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host supdepub.fr not found: 2(SERVFAIL)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host supdepub.fr not found: 2(SERVFAIL)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host supdepub.fr not found: 2(SERVFAIL)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host supdepub.fr not found: 2(SERVFAIL)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host supdepub.fr not found: 2(SERVFAIL)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host supdepub.fr not found: 2(SERVFAIL)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host supdepub.fr not found: 2(SERVFAIL)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host supdepub.fr not found: 2(SERVFAIL)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host supdepub.fr not found: 2(SERVFAIL)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host supdepub.fr not found: 2(SERVFAIL)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host supdepub.fr not found: 2(SERVFAIL)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host alunofpb not found: 2(SERVFAIL)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Pull request closed without merging**
