### PR TITLE
Create test1.txt

### PR DESCRIPTION
**Pull request by philipto1**

### CODE REVIEW

**Comment by philipto1** [comment]
test

**Comment by philipto** [comment]
Filename is incorrect

**Comment by philipto** [comment]
BEloze

**Comment by philipto** [comment]
$TXT_PATH_INCORRECT

**Comment by philipto** [comment]
$TXT_PATH_INCORRECT

**Comment by philipto** [comment]
$TXT_PATH_INCORRECT

**Comment by philipto** [comment]
$TXT_PATH_INCORRECT

**Comment by philipto** [comment]
$TXT_PATH_INCORRECT

**Comment by philipto** [comment]
$TXT_PATH_INCORRECT

**Comment by philipto** [comment]
$TXT_PATH_INCORRECT

**Comment by philipto** [comment]
text

**Comment by philipto** [comment]
text

**Comment by philipto** [comment]
text

**Comment by philipto** [comment]
text

**Comment by philipto** [comment]
text

**Comment by philipto** [comment]
text

**Comment by philipto** [comment]
TXT_NONEXISTENT_HOST

**Comment by philipto** [comment]
text

**Comment by philipto** [comment]
TXT_NONEXISTENT_HOST

**Comment by philipto** [comment]
TXT_NONEXISTENT_HOST

**Comment by philipto** [comment]
The domain does not exist: Host BEZO.ca not found: 3(NXDOMAIN)

**Comment by philipto** [comment]
The domain does not exist: Host beshbarma.ca not found: 3(NXDOMAIN)

**Comment by philipto** [comment]
The domain test1.ca is in the blacklist, sorry.

**Comment by philipto** [comment]
The domain does not exist: Host 1.cu not found: 3(NXDOMAIN)

**Comment by philipto** [comment]
The domain does not exist: Host BEZO.ca not found: 3(NXDOMAIN)

**Comment by philipto** [comment]
The domain does not exist: Host beshbarma.ca not found: 3(NXDOMAIN)

**Comment by philipto** [comment]
The domain test1.ca is in the blacklist, sorry.

**Comment by philipto** [comment]
The domain does not exist: Host 1.cu not found: 3(NXDOMAIN)

**Comment by philipto** [comment]
lib/domains/ca/BASE path is incorrect

**Comment by philipto** [comment]
lib/domains/ca/BEZO.txt path is incorrect

**Comment by philipto** [comment]
The domain does not exist: Host BEZO.ca not found: 3(NXDOMAIN)

**Comment by philipto** [comment]
lib/domains/ca/beshbarma path is incorrect

**Comment by philipto** [comment]
The domain does not exist: Host beshbarma.ca not found: 3(NXDOMAIN)

**Comment by philipto** [comment]
The domain test1.ca is in the blacklist, sorry.

**Comment by philipto** [comment]
The domain does not exist: Host 1.cu not found: 3(NXDOMAIN)

**Comment by philipto** [comment]
lib/domains/ca/BASE path is incorrect

**Comment by philipto** [comment]
lib/domains/ca/BEZO.txt path is incorrect

**Comment by philipto** [comment]
The domain does not exist: Host BEZO.ca not found: 3(NXDOMAIN)

**Comment by philipto** [comment]
lib/domains/ca/beshbarma path is incorrect

**Comment by philipto** [comment]
The domain does not exist: Host beshbarma.ca not found: 3(NXDOMAIN)

**Comment by philipto** [comment]
The domain test1.ca is in the blacklist, sorry.

**Comment by philipto** [comment]
The domain does not exist: Host 1.cu not found: 3(NXDOMAIN)

**Comment by philipto** [comment]
lib/domains/ca/BASE path is incorrect

**Comment by philipto** [comment]
lib/domains/ca/BEZO.txt path is incorrect

**Comment by philipto** [comment]
The domain does not exist: Host BEZO.ca not found: 3(NXDOMAIN)

**Comment by philipto** [comment]
lib/domains/ca/beshbarma path is incorrect

**Comment by philipto** [comment]
The domain does not exist: Host beshbarma.ca not found: 3(NXDOMAIN)

**Comment by philipto** [comment]
The domain test1.ca is in the blacklist, sorry.

**Comment by philipto** [comment]
The domain does not exist: Host 1.cu not found: 3(NXDOMAIN)

**Comment by philipto** [comment]
lib/domains/ca/BASE path is incorrect

**Comment by philipto** [comment]
lib/domains/ca/BEZO.txt path is incorrect

**Comment by philipto** [comment]
lib/domains/ca/beshbarma path is incorrect

**Comment by philipto** [comment]
The domain test1.ca is in the blacklist, sorry.

**Comment by philipto** [comment]
lib/domains/ca/BASE path is incorrect

**Comment by philipto** [comment]
lib/domains/ca/BEZO.txt path is incorrect

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: Host BEZO.ca not found: 3(NXDOMAIN) Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
lib/domains/ca/beshbarma path is incorrect

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: Host beshbarma.ca not found: 3(NXDOMAIN) Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
The domain test1.ca is in the blacklist, sorry.

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: Host 1.cu not found: 3(NXDOMAIN) Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
lib/domains/ca/BASE path is incorrect

**Comment by philipto** [comment]
lib/domains/ca/BEZO.txt path is incorrect

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: Host BEZO.ca not found: 3(NXDOMAIN) Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
lib/domains/ca/beshbarma path is incorrect

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: Host beshbarma.ca not found: 3(NXDOMAIN) Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
lib/domains/ca/best.txt path is incorrect

**Comment by philipto** [comment]
lib/domains/ca/test1.txt path is incorrect

**Comment by philipto** [comment]
The domain test1.ca is in the blacklist, sorry.

**Comment by philipto** [comment]
lib/domains/cu/1.txt path is incorrect

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: Host 1.cu not found: 3(NXDOMAIN) Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host BEZO.ca not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host beshbarma.ca not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host 1.cu not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host BEZO.ca not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host beshbarma.ca not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host 1.cu not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host BEZO.ca not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host beshbarma.ca not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host 1.cu not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host BEZO.ca not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host beshbarma.ca not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host 1.cu not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Pull request closed without merging**
